version: "3.9"
services:
  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker:1.0.1
    ports:
      - "61616:61616"
      - "5672:5672"
      - "8161:8161"
    environment:
      AMQ_USER: "quarkus"
      AMQ_PASSWORD: "quarkus"
      AMQ_EXTRA_ARGS: "--relax-jolokia"