name: ci-quarkus-native

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/ci-quarkus-native.yml"
      - "microservices/veljavnost/**"
  pull_request:
    branches: [main]

permissions:
  packages: write

concurrency:
  group: ci-quarkus-native

jobs:
  build-native:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: login ghcr.io
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true
      - name: checkout
        uses: actions/checkout@v2
      - name: gradle build push native
        run: cd microservices/veljavnost/ && ./mvnw build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
      - name: docker build
        run:  docker build -f microservices/veljavnost/src/main/docker/Dockerfile.native-micro -t ghcr.io/kukovecrok/veljavnost-native:latest microservices/veljavnost/
      - name: docker push
        run: docker image push ghcr.io/kukovecrok/veljavnost-native:latest

