name: ci-quarkus-native

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/ci-quarkus-native.yml"
      - "microservices/veljavnost/**"
  pull_request:
    branches: [main]

permissions:
  packages: write

concurrency:
  group: ci-quarkus-native

jobs:
  build-native:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: login ghcr.io
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2
      - name: chmod
        run: chmod +x microservices/veljavnost/mvnw
      - name: maven build
        run: cd microservices/veljavnost/ && mvn package 
      - name: docker build
        run:  docker build -f microservices/veljavnost/src/main/docker/Dockerfile.jvm -t ghcr.io/kukovecrok/veljavnost:latest microservices/veljavnost/
      - name: docker push
        run: docker image push ghcr.io/kukovecrok/veljavnost:latest

